### ISSUE TITLE
Ne pas importer les thèmes dans components

### ISSUE THREAD

**Issue by florian-lefebvre** [EduWireApps/ynotes-components#1]
Actuellement, `components` importe directement les thèmes, ce qui empêche son utilisation en dehors de yNotes. Il faudrait donc passer les thèmes à la lib dans l'application.

Je suppose que le mieux c'est de passer les thèmes dans le main avec une fonction d'initialisation genre:
```dart
void main() {
    final List<YTheme> themes = [systemTheme, lightTheme, darkTheme];
    components.init(themes)
}
```

Ça voudrait dire qu'on ne peut pas utiliser d'énumération (YAvailableTheme).

En sachant qu'il faut pouvoir accéder à `theme` depuis le package `ynotes_packages/theme.dart` et non pas l'application.

T'en penses quoi @Androz2091 ?

**Comment by florian-lefebvre** [comment]
Autre possibilité, c'est de créer un widget au root de l'app comme MaterialApp, mais je suppose que ça n'a du sens que lorsqu'on fait passer des infos via le contexte.

**Comment by Androz2091** [comment]
Un enum c'est bien pour un switch case ou un if, c'est plus propre, mais ça ne devrait pas être le cas dans les composants. On ne devrait pas se baser sur le nom pour décider si il y a un darkmode, ou autre 
```dart
switch (themeActuel) {
    case MyThemeEnum.dark:
        print('black');
        break;
    case MyThemeEnum.light:
         print('white');
         break;
// etc...
// je pense que le mieux, ce serait
print(themeActuel.color);
```
bref, s'il n'y a pas de logique qui se base sur le nom du thème actuel, je ne vois pas l'intérêt d'un enum, donc ce n'est pas grave si on l'enlève

et je pense que tu connais mieux Flutter et le Dart que moi, donc fais comme bon te semble ;)

**Comment by florian-lefebvre** [comment]
ça marche ! 👍 je vais faire des tests mais j'ai déjà une idée

**Comment by florian-lefebvre** [comment]
C'est bon ! Maintenant les thèmes sont définis dans l'application et non plus dans le package. Il faut les initaliser dans la main function:
```dart
import 'package:ynotes_packages/theme.dart';
import 'themes/themes.dart';

void main() {
    themes = YCurrenTheme(currentTheme: 0, themes: themes);
}
```
